using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BarIceCreamShop.Api.Models;
[Table("producto_componentes")] public class ProductComponent { [Column("id_producto_compuesto")] public int CompositeProductId {get;set;} [Column("id_producto_componente")] public int ComponentProductId {get;set;} [Column("cantidad",TypeName="decimal(18,3)")] public decimal Quantity {get;set;} }
[Table("movimientos_stock")] public class StockMovement { [Column("id_movimiento_stock")] public int Id {get;set;} [Column("id_empresa")] public int CompanyId {get;set;} [Column("id_sucursal")] public int BranchId {get;set;} [Column("id_producto")] public int ProductId {get;set;} [Column("tipo")] public string Type {get;set;}="Ingreso"; [Column("cantidad",TypeName="decimal(18,3)")] public decimal Quantity {get;set;} [Column("stock_anterior",TypeName="decimal(18,3)")] public decimal PreviousStock {get;set;} [Column("stock_nuevo",TypeName="decimal(18,3)")] public decimal NewStock {get;set;} [Column("origen")] public string Source {get;set;}="Manual"; [Column("id_referencia")] public int? ReferenceId {get;set;} [Column("observacion")] public string? Note {get;set;} [Column("id_usuario")] public int UserId {get;set;} [Column("fecha")] public DateTime Date {get;set;} }
public class StockAdjustmentRequest { [Range(1,int.MaxValue)] public int ProductId {get;set;} [Required] public string Type {get;set;}="Ingreso"; [Range(typeof(decimal),"0.001","999999999999999.999")] public decimal Quantity {get;set;} [MaxLength(500)] public string? Note {get;set;} }
public class ProductComponentRequest { [Range(1,int.MaxValue)] public int ProductId {get;set;} [Range(typeof(decimal),"0.001","999999999999999.999")] public decimal Quantity {get;set;} }
public record StockMovementDto(int Id,DateTime Date,int ProductId,string ProductName,string Type,decimal Quantity,decimal PreviousStock,decimal NewStock,string Source,int? ReferenceId,string? Note,string UserName);
public record ProductComponentDto(int ProductId,string Name,decimal Quantity);
