using System.Data;using BarIceCreamShop.Api.Data;using BarIceCreamShop.Api.Models;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;
namespace BarIceCreamShop.Api.Services;
public sealed class CustomerService(AppDbContext db){
 public async Task<List<CustomerDto>>List(int company,string?search,bool includeInactive){var q=db.Customers.AsNoTracking().Where(x=>x.CompanyId==company&&(includeInactive||x.Active));if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim();q=q.Where(x=>EF.Functions.ILike(x.Name,$"%{s}%")||x.DocumentNumber!=null&&EF.Functions.ILike(x.DocumentNumber,$"%{s}%")||x.Phone!=null&&EF.Functions.ILike(x.Phone,$"%{s}%"));}return await q.OrderBy(x=>x.Name).Select(x=>Dto(x)).ToListAsync();}
 public async Task<CustomerDto?>Get(int company,int id)=>await db.Customers.AsNoTracking().Where(x=>x.CompanyId==company&&x.Id==id).Select(x=>Dto(x)).SingleOrDefaultAsync();
 public async Task<CustomerDto>Create(int company,CustomerRequest r){Validate(r);await Unique(company,r,null);await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var now=DateTime.UtcNow;var x=new Customer{CompanyId=company,Code=await NextCode(company,tx),CreatedAt=now};Apply(x,r,now);db.Customers.Add(x);await db.SaveChangesAsync();await tx.CommitAsync();return Dto(x);}
 public async Task<CustomerDto>Update(int company,int id,CustomerRequest r){Validate(r);var x=await db.Customers.SingleOrDefaultAsync(x=>x.CompanyId==company&&x.Id==id)??throw new SaleException("Cliente no encontrado.",404);await Unique(company,r,id);Apply(x,r,DateTime.UtcNow);await db.SaveChangesAsync();return Dto(x);}
 public async Task<CustomerDto>Status(int company,int id,bool active){var x=await db.Customers.SingleOrDefaultAsync(x=>x.CompanyId==company&&x.Id==id)??throw new SaleException("Cliente no encontrado.",404);x.Active=active;x.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Dto(x);}
 private async Task Unique(int company,CustomerRequest r,int?id){var number=Clean(r.DocumentNumber);if(number!=null&&await db.Customers.AnyAsync(x=>x.CompanyId==company&&x.Id!=id&&x.DocumentType==r.DocumentType&&x.DocumentNumber==number))throw new SaleException("Ya existe un cliente con ese documento.",409);}
 private static void Validate(CustomerRequest r){if(string.IsNullOrWhiteSpace(r.Name))throw new SaleException("El nombre es obligatorio.");if(r.Birthday>DateOnly.FromDateTime(DateTime.Today))throw new SaleException("El cumpleaños no puede ser futuro.");}
 private static void Apply(Customer x,CustomerRequest r,DateTime now){x.Name=r.Name.Trim();x.PriceList=r.PriceList.Trim();x.VatCondition=r.VatCondition.Trim();x.DocumentType=r.DocumentType.Trim();x.DocumentNumber=Clean(r.DocumentNumber);x.Phone=Clean(r.Phone);x.Email=Clean(r.Email)?.ToLowerInvariant();x.Birthday=r.Birthday;x.Active=r.Active;x.UpdatedAt=now;}
 private static string?Clean(string?v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();private static CustomerDto Dto(Customer x)=>new(x.Id,x.Code,x.Name,x.PriceList,x.VatCondition,x.DocumentType,x.DocumentNumber,x.Phone,x.Email,x.Birthday,x.Active);
 private async Task<int>NextCode(int company,IDbContextTransaction tx){await using var c=db.Database.GetDbConnection().CreateCommand();c.Transaction=tx.GetDbTransaction();c.CommandText="INSERT INTO cliente_contadores(id_empresa,ultimo_codigo) VALUES(@id,1) ON CONFLICT(id_empresa) DO UPDATE SET ultimo_codigo=cliente_contadores.ultimo_codigo+1 RETURNING ultimo_codigo";var p=c.CreateParameter();p.ParameterName="id";p.Value=company;c.Parameters.Add(p);return Convert.ToInt32(await c.ExecuteScalarAsync());}}
