BEGIN;

UPDATE mesas SET estado = 'Libre' WHERE estado = 'Disponible';
ALTER TABLE mesas ALTER COLUMN estado SET DEFAULT 'Libre';

CREATE TABLE IF NOT EXISTS descuentos (
    id_descuento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    descripcion varchar(500),
    tipo varchar(20) NOT NULL CHECK (tipo IN ('Porcentaje','Importe')),
    valor numeric(18,2) NOT NULL CHECK (valor >= 0),
    activo boolean NOT NULL DEFAULT true,
    vigente_desde timestamp with time zone,
    vigente_hasta timestamp with time zone,
    CHECK (tipo <> 'Porcentaje' OR valor <= 100),
    CHECK (vigente_hasta IS NULL OR vigente_desde IS NULL OR vigente_hasta >= vigente_desde)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_descuentos_empresa_nombre_ci ON descuentos(id_empresa, lower(nombre));

CREATE TABLE IF NOT EXISTS tipos_cobro (
    id_tipo_cobro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(100) NOT NULL,
    activo boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tipos_cobro_global_nombre_ci ON tipos_cobro(lower(nombre)) WHERE id_empresa IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_tipos_cobro_empresa_nombre_ci ON tipos_cobro(id_empresa, lower(nombre)) WHERE id_empresa IS NOT NULL;
INSERT INTO tipos_cobro(id_empresa,nombre) SELECT NULL,v.nombre FROM (VALUES ('Efectivo'),('Tarjeta'),('Transferencia'),('QR')) v(nombre)
WHERE NOT EXISTS (SELECT 1 FROM tipos_cobro t WHERE t.id_empresa IS NULL AND lower(t.nombre)=lower(v.nombre));

CREATE TABLE IF NOT EXISTS venta_contadores (
    id_empresa integer PRIMARY KEY REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    ultimo_numero_venta integer NOT NULL DEFAULT 0,
    ultimo_numero_comanda integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ventas (
    id_venta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    numero integer NOT NULL,
    id_mesa integer NOT NULL REFERENCES mesas(id_mesa) ON DELETE RESTRICT,
    id_mozo integer REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    estado varchar(30) NOT NULL CHECK (estado IN ('Abierta','EnPedido','PedidoEnviado','ConCambios','Finalizada','Cancelada')),
    fecha_apertura timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre timestamp with time zone,
    subtotal numeric(18,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    importe_descuento numeric(18,2) NOT NULL DEFAULT 0 CHECK (importe_descuento >= 0),
    total numeric(18,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    id_usuario_apertura integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    id_usuario_cobro integer REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    id_descuento integer REFERENCES descuentos(id_descuento) ON DELETE RESTRICT,
    descuento_nombre varchar(150), descuento_tipo varchar(20),
    descuento_valor numeric(18,2), version bigint NOT NULL DEFAULT 1,
    CONSTRAINT ux_ventas_empresa_numero UNIQUE(id_empresa,numero)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ventas_mesa_activa ON ventas(id_mesa) WHERE estado IN ('Abierta','EnPedido','PedidoEnviado','ConCambios');
CREATE INDEX IF NOT EXISTS ix_ventas_empresa_sucursal_estado ON ventas(id_empresa,id_sucursal,estado);

CREATE TABLE IF NOT EXISTS venta_items (
    id_venta_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
    id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
    producto_nombre varchar(200) NOT NULL,
    precio_unitario numeric(18,2) NOT NULL CHECK(precio_unitario>=0),
    cantidad numeric(18,3) NOT NULL CHECK(cantidad>0),
    subtotal numeric(18,2) NOT NULL CHECK(subtotal>=0),
    comentario varchar(500), estado varchar(30) NOT NULL DEFAULT 'Activo',
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_venta_items_producto UNIQUE(id_venta,id_producto)
);

CREATE TABLE IF NOT EXISTS comandas (
    id_comanda integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    numero integer NOT NULL, id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
    id_mesa integer NOT NULL REFERENCES mesas(id_mesa) ON DELETE RESTRICT,
    id_mozo integer REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    tipo varchar(20) NOT NULL CHECK(tipo IN ('Inicial','Modificación')),
    fecha timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    CONSTRAINT ux_comandas_empresa_numero UNIQUE(id_empresa,numero)
);

CREATE TABLE IF NOT EXISTS comanda_renglones (
    id_comanda_renglon integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comanda integer NOT NULL REFERENCES comandas(id_comanda) ON DELETE CASCADE,
    id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
    producto_nombre varchar(200) NOT NULL,
    variacion_cantidad numeric(18,3) NOT NULL,
    cantidad_actual numeric(18,3) NOT NULL,
    comentario varchar(500)
);

CREATE TABLE IF NOT EXISTS venta_pagos (
    id_pago integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
    id_tipo_cobro integer NOT NULL REFERENCES tipos_cobro(id_tipo_cobro) ON DELETE RESTRICT,
    tipo_cobro_nombre varchar(100) NOT NULL,
    importe numeric(18,2) NOT NULL CHECK(importe>0),
    fecha timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    referencia varchar(500)
);

CREATE TABLE IF NOT EXISTS venta_mesas_unidas (
    id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
    id_mesa integer NOT NULL REFERENCES mesas(id_mesa) ON DELETE RESTRICT,
    PRIMARY KEY(id_venta,id_mesa)
);

COMMIT;
