BEGIN;

CREATE TABLE IF NOT EXISTS stock_productos (
    id_stock_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE CASCADE,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    operacion_cantidad varchar(20) NOT NULL DEFAULT 'Entero'
        CHECK (operacion_cantidad IN ('Entero', 'Decimal')),
    stock_actual numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    stock_minimo numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    stock_ideal numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_ideal >= stock_minimo),
    tiene_alarma_stock boolean NOT NULL DEFAULT false,
    tiene_alarma_stock_minimo boolean NOT NULL DEFAULT false,
    comprobar_stock_al_vender boolean NOT NULL DEFAULT false,
    actualizar_sobre varchar(20) NOT NULL DEFAULT 'Producto'
        CHECK (actualizar_sobre IN ('Producto', 'Ingrediente')),
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_stock_productos_producto_sucursal UNIQUE (id_producto, id_sucursal)
);

CREATE INDEX IF NOT EXISTS ix_stock_productos_sucursal ON stock_productos(id_sucursal);

COMMIT;
