BEGIN;
CREATE TABLE IF NOT EXISTS producto_componentes (
 id_producto_compuesto integer NOT NULL REFERENCES productos(id_producto) ON DELETE CASCADE,
 id_producto_componente integer NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
 cantidad numeric(18,3) NOT NULL CHECK(cantidad>0),
 PRIMARY KEY(id_producto_compuesto,id_producto_componente),
 CHECK(id_producto_compuesto<>id_producto_componente)
);
CREATE TABLE IF NOT EXISTS movimientos_stock (
 id_movimiento_stock integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_empresa integer NOT NULL REFERENCES empresas(id_empresa), id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal),
 id_producto integer NOT NULL REFERENCES productos(id_producto), tipo varchar(20) NOT NULL CHECK(tipo IN ('Ingreso','Egreso','Ajuste')),
 cantidad numeric(18,3) NOT NULL CHECK(cantidad>0), stock_anterior numeric(18,3) NOT NULL, stock_nuevo numeric(18,3) NOT NULL CHECK(stock_nuevo>=0),
 origen varchar(20) NOT NULL CHECK(origen IN ('Manual','Venta','Compuesto')),
 id_referencia integer NULL, observacion varchar(500) NULL, id_usuario integer NOT NULL REFERENCES usuarios(id_usuario), fecha timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_movimientos_stock_consulta ON movimientos_stock(id_empresa,id_sucursal,fecha DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_movimientos_stock_venta_producto ON movimientos_stock(id_sucursal,id_producto,origen,id_referencia) WHERE origen IN ('Venta','Compuesto') AND id_referencia IS NOT NULL;
COMMIT;
