BEGIN;

CREATE TABLE IF NOT EXISTS cajas (
    id_caja integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    estado varchar(20) NOT NULL DEFAULT 'Abierta' CHECK (estado IN ('Abierta','Cerrada')),
    id_usuario_apertura integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    fecha_apertura timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_inicial numeric(18,2) NOT NULL DEFAULT 0 CHECK (monto_inicial >= 0),
    id_usuario_cierre integer REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    fecha_cierre timestamp with time zone,
    total_ventas numeric(18,2),
    total_ingresos numeric(18,2),
    total_egresos numeric(18,2),
    total_efectivo_esperado numeric(18,2),
    observaciones varchar(1000),
    CHECK (estado = 'Abierta' OR (fecha_cierre IS NOT NULL AND id_usuario_cierre IS NOT NULL))
);

-- Sólo puede haber una caja abierta a la vez por sucursal.
CREATE UNIQUE INDEX IF NOT EXISTS ux_cajas_sucursal_abierta
    ON cajas (id_sucursal) WHERE estado = 'Abierta';
CREATE INDEX IF NOT EXISTS ix_cajas_empresa_sucursal_fecha
    ON cajas (id_empresa, id_sucursal, fecha_apertura DESC);

CREATE TABLE IF NOT EXISTS caja_movimientos (
    id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caja integer NOT NULL REFERENCES cajas(id_caja) ON DELETE CASCADE,
    tipo varchar(20) NOT NULL CHECK (tipo IN ('Ingreso','Egreso')),
    monto numeric(18,2) NOT NULL CHECK (monto > 0),
    motivo varchar(255) NOT NULL,
    id_usuario integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    fecha timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_caja_movimientos_caja ON caja_movimientos (id_caja, fecha);

-- Snapshot de ventas por medio de pago al momento del cierre (no varía si luego cambia el catálogo).
CREATE TABLE IF NOT EXISTS caja_cierre_detalle (
    id_caja integer NOT NULL REFERENCES cajas(id_caja) ON DELETE CASCADE,
    medio_pago varchar(150) NOT NULL,
    total numeric(18,2) NOT NULL,
    PRIMARY KEY (id_caja, medio_pago)
);

COMMIT;
