BEGIN;

CREATE TABLE IF NOT EXISTS listas_precios (
    id_lista_precio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    es_predeterminada boolean NOT NULL DEFAULT false,
    activa boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_listas_precios_empresa_nombre_ci
    ON listas_precios(id_empresa, lower(nombre));
-- Una sola lista predeterminada por empresa.
CREATE UNIQUE INDEX IF NOT EXISTS ux_listas_precios_predeterminada
    ON listas_precios(id_empresa) WHERE es_predeterminada;

CREATE TABLE IF NOT EXISTS producto_precios (
    id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE CASCADE,
    id_lista_precio integer NOT NULL REFERENCES listas_precios(id_lista_precio) ON DELETE CASCADE,
    precio numeric(18,2) NOT NULL CHECK (precio >= 0),
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_producto, id_lista_precio)
);
CREATE INDEX IF NOT EXISTS ix_producto_precios_lista ON producto_precios(id_lista_precio);

-- Sucursal opcionalmente puede fijar su propia lista predeterminada.
ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS id_lista_precio_predeterminada
    integer REFERENCES listas_precios(id_lista_precio) ON DELETE SET NULL;

-- Trazabilidad histórica: qué lista se usó para cada venta/renglón vendido.
-- RESTRICT a propósito: impide borrar una lista que ya fue usada en ventas.
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS id_lista_precio
    integer REFERENCES listas_precios(id_lista_precio) ON DELETE RESTRICT;
ALTER TABLE venta_items ADD COLUMN IF NOT EXISTS id_lista_precio
    integer REFERENCES listas_precios(id_lista_precio) ON DELETE RESTRICT;

-- Backfill: toda empresa existente recibe su lista General (predeterminada),
-- con los precios que ya tenían cargados sus productos.
INSERT INTO listas_precios (id_empresa, nombre, es_predeterminada, activa)
SELECT e.id_empresa, 'General', true, true
FROM empresas e
WHERE NOT EXISTS (
    SELECT 1 FROM listas_precios l WHERE l.id_empresa = e.id_empresa AND l.es_predeterminada
);

INSERT INTO producto_precios (id_producto, id_lista_precio, precio)
SELECT p.id_producto, l.id_lista_precio, p.precio_con_iva
FROM productos p
JOIN listas_precios l ON l.id_empresa = p.id_empresa AND l.es_predeterminada
WHERE NOT EXISTS (
    SELECT 1 FROM producto_precios pp WHERE pp.id_producto = p.id_producto AND pp.id_lista_precio = l.id_lista_precio
);

UPDATE ventas v SET id_lista_precio = l.id_lista_precio
FROM listas_precios l
WHERE l.id_empresa = v.id_empresa AND l.es_predeterminada AND v.id_lista_precio IS NULL;

UPDATE venta_items vi SET id_lista_precio = v.id_lista_precio
FROM ventas v
WHERE v.id_venta = vi.id_venta AND v.id_lista_precio IS NOT NULL AND vi.id_lista_precio IS NULL;

-- Garantiza la lista General ante cualquier alta futura de empresa (no hay
-- endpoint de alta de empresas en la API; se crean directamente en la base).
CREATE OR REPLACE FUNCTION fn_crear_lista_precios_general() RETURNS trigger AS $$
BEGIN
    INSERT INTO listas_precios (id_empresa, nombre, es_predeterminada, activa)
    VALUES (NEW.id_empresa, 'General', true, true);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_empresas_crear_lista_general ON empresas;
CREATE TRIGGER trg_empresas_crear_lista_general
AFTER INSERT ON empresas
FOR EACH ROW EXECUTE FUNCTION fn_crear_lista_precios_general();

COMMIT;
