BEGIN;
CREATE TABLE IF NOT EXISTS reglas_precio (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_lista_precio integer NOT NULL REFERENCES listas_precios(id_lista_precio) ON DELETE CASCADE,
    nombre varchar(150) NOT NULL,
    activa boolean NOT NULL DEFAULT true,
    prioridad integer NOT NULL DEFAULT 0 CHECK (prioridad BETWEEN 0 AND 10000),
    id_producto integer REFERENCES productos(id_producto) ON DELETE RESTRICT,
    id_rubro integer REFERENCES rubros(id_rubro) ON DELETE RESTRICT,
    id_subrubro integer REFERENCES subrubros(id_subrubro) ON DELETE RESTRICT,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    dias_semana integer NOT NULL DEFAULT 127 CHECK (dias_semana BETWEEN 1 AND 127),
    minuto_desde integer CHECK (minuto_desde BETWEEN 0 AND 1439),
    minuto_hasta integer CHECK (minuto_hasta BETWEEN 0 AND 1439),
    operacion varchar(30) NOT NULL CHECK (operacion IN ('PrecioFijo','AumentarPorcentaje','DisminuirPorcentaje','AumentarImporte','DisminuirImporte')),
    valor numeric(18,2) NOT NULL CHECK (valor >= 0),
    redondeo numeric(18,2) NOT NULL DEFAULT 0 CHECK (redondeo BETWEEN 0 AND 1000000),
    modo_redondeo varchar(10) NOT NULL DEFAULT 'Arriba' CHECK (modo_redondeo IN ('Arriba','Abajo','Cercano')),
    version integer NOT NULL DEFAULT 1,
    usuario text NOT NULL,
    fecha_modificacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (num_nonnulls(id_producto, id_rubro, id_subrubro) <= 1),
    CHECK (fecha_hasta IS NULL OR fecha_hasta >= fecha_desde),
    CHECK ((minuto_desde IS NULL AND minuto_hasta IS NULL) OR
        (minuto_desde IS NOT NULL AND minuto_hasta IS NOT NULL AND minuto_desde <> minuto_hasta))
);
CREATE INDEX IF NOT EXISTS ix_reglas_precio_lista ON reglas_precio(id_empresa, id_lista_precio, activa);
GRANT SELECT, INSERT, UPDATE ON reglas_precio TO foco_api;
GRANT USAGE, SELECT ON SEQUENCE reglas_precio_id_seq TO foco_api;
COMMIT;
