BEGIN;
ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS google_sheet_id varchar(200) NULL;

CREATE TABLE IF NOT EXISTS google_sheet_jobs(
  id_google_sheet_job integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
  id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE CASCADE,
  estado varchar(20) NOT NULL DEFAULT 'Pendiente',
  intentos integer NOT NULL DEFAULT 0,
  error varchar(500) NULL,
  fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_google_sheet_jobs_estado ON google_sheet_jobs(estado, fecha_creacion);
COMMIT;
