BEGIN;

CREATE TABLE IF NOT EXISTS impresoras (
    id_impresora integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    tipo_conexion varchar(20) NOT NULL CHECK (tipo_conexion IN ('Cups', 'Red')),
    nombre_cola varchar(200) NULL,
    direccion_ip varchar(45) NULL,
    puerto integer NULL CHECK (puerto IS NULL OR puerto BETWEEN 1 AND 65535),
    uso varchar(20) NOT NULL CHECK (uso IN ('Comanda', 'TicketVenta', 'Ambos')),
    predeterminada boolean NOT NULL DEFAULT false,
    activa boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_impresoras_conexion CHECK (
        (tipo_conexion = 'Cups' AND nombre_cola IS NOT NULL AND btrim(nombre_cola) <> '')
        OR (tipo_conexion = 'Red' AND direccion_ip IS NOT NULL AND btrim(direccion_ip) <> '' AND puerto IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_impresoras_sucursal_nombre_ci
    ON impresoras (id_sucursal, lower(nombre));
CREATE INDEX IF NOT EXISTS ix_impresoras_empresa_sucursal_uso
    ON impresoras (id_empresa, id_sucursal, uso, activa);

ALTER TABLE trabajos_impresion
    ADD COLUMN IF NOT EXISTS id_impresora_configuracion integer NULL
        REFERENCES impresoras(id_impresora) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_trabajos_impresion_configuracion
    ON trabajos_impresion(id_impresora_configuracion);

COMMIT;
