BEGIN;

CREATE TABLE IF NOT EXISTS tarjetas (
    id_tarjeta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    descripcion varchar(500) NULL,
    tipo_ajuste varchar(20) NOT NULL DEFAULT 'SinAjuste'
        CHECK (tipo_ajuste IN ('SinAjuste', 'Descuento', 'Recargo')),
    porcentaje numeric(5,2) NOT NULL DEFAULT 0
        CHECK (porcentaje >= 0 AND porcentaje <= 100),
    activa boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_tarjetas_ajuste_porcentaje CHECK (
        (tipo_ajuste = 'SinAjuste' AND porcentaje = 0)
        OR (tipo_ajuste IN ('Descuento', 'Recargo') AND porcentaje > 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tarjetas_empresa_nombre_ci
    ON tarjetas (id_empresa, lower(nombre));
CREATE INDEX IF NOT EXISTS ix_tarjetas_empresa_activa
    ON tarjetas (id_empresa, activa, nombre);

COMMIT;
