BEGIN;

CREATE TABLE IF NOT EXISTS mesas (
    id_mesa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    id_sector integer NOT NULL REFERENCES sectores(id_sector) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    descripcion varchar(1000) NULL,
    forma varchar(30) NOT NULL DEFAULT 'Rectangular'
        CHECK (forma IN ('Circular', 'Cuadrada', 'Rectangular')),
    capacidad integer NOT NULL CHECK (capacidad > 0),
    posicion_x numeric(8,6) NOT NULL DEFAULT 0 CHECK (posicion_x >= 0 AND posicion_x <= 1),
    posicion_y numeric(8,6) NOT NULL DEFAULT 0 CHECK (posicion_y >= 0 AND posicion_y <= 1),
    numero integer NOT NULL DEFAULT 0 CHECK (numero >= 0),
    estado varchar(30) NOT NULL DEFAULT 'Libre',
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mesas_sucursal_nombre_ci
    ON mesas (id_sucursal, lower(nombre));
CREATE INDEX IF NOT EXISTS ix_mesas_empresa_sucursal_sector
    ON mesas (id_empresa, id_sucursal, id_sector);

COMMIT;
