BEGIN;

CREATE TABLE IF NOT EXISTS sectores (
    id_sector integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(150) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    orden integer NOT NULL DEFAULT 0 CHECK (orden >= 0),
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sectores_empresa_nombre_ci
    ON sectores (id_empresa, lower(nombre));
CREATE INDEX IF NOT EXISTS ix_sectores_empresa_orden
    ON sectores (id_empresa, orden, nombre);

COMMIT;
