BEGIN;

CREATE TABLE IF NOT EXISTS trabajos_impresion (
    id_trabajo_impresion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
    id_impresora varchar(200) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado varchar(30) NOT NULL DEFAULT 'Pendiente',
    tipo varchar(30) NOT NULL DEFAULT 'Comanda'
);

ALTER TABLE trabajos_impresion
    ADD COLUMN IF NOT EXISTS tipo varchar(30) NOT NULL DEFAULT 'Comanda';

ALTER TABLE trabajos_impresion DROP CONSTRAINT IF EXISTS trabajos_impresion_tipo_check;
ALTER TABLE trabajos_impresion ADD CONSTRAINT trabajos_impresion_tipo_check
    CHECK (tipo IN ('Comanda', 'TicketVenta'));

CREATE INDEX IF NOT EXISTS ix_trabajos_impresion_venta
    ON trabajos_impresion(id_venta);
CREATE INDEX IF NOT EXISTS ix_trabajos_impresion_estado
    ON trabajos_impresion(estado, fecha_creacion);

COMMIT;
