BEGIN;
CREATE TABLE IF NOT EXISTS cliente_contadores(id_empresa integer PRIMARY KEY REFERENCES empresas(id_empresa) ON DELETE CASCADE,ultimo_codigo integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS clientes(
 id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,codigo integer NOT NULL CHECK(codigo>0),
 nombre varchar(200) NOT NULL,lista_precios varchar(100) NOT NULL DEFAULT 'Predeterminada',condicion_iva varchar(100) NOT NULL DEFAULT 'Consumidor Final',
 tipo_documento varchar(30) NOT NULL DEFAULT 'DNI',numero_documento varchar(30) NULL,telefono varchar(50) NULL,email varchar(200) NULL,cumpleanos date NULL,
 activo boolean NOT NULL DEFAULT true,fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_empresa,codigo)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_clientes_empresa_documento ON clientes(id_empresa,tipo_documento,numero_documento) WHERE numero_documento IS NOT NULL AND btrim(numero_documento)<>'';
CREATE INDEX IF NOT EXISTS ix_clientes_empresa_nombre ON clientes(id_empresa,nombre);
COMMIT;
