BEGIN;

-- Catálogos mínimos requeridos por Producto. No se exponen endpoints para ellos.
CREATE TABLE IF NOT EXISTS rubros (
    id_rubro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(200) NOT NULL,
    descripcion varchar(2000) NULL,
    tipo_observacion varchar(50) NOT NULL DEFAULT 'SinObservaciones',
    imagen_url text NULL,
    aplicar_productos boolean NOT NULL DEFAULT true,
    aplicar_delivery boolean NOT NULL DEFAULT false,
    aplicar_salon boolean NOT NULL DEFAULT false,
    mostrar_carta_digital boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_rubros_empresa ON rubros(id_empresa);

CREATE TABLE IF NOT EXISTS subrubros (
    id_subrubro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_rubro integer NOT NULL REFERENCES rubros(id_rubro) ON DELETE RESTRICT,
    nombre varchar(200) NOT NULL,
    descripcion varchar(2000) NULL,
    tipo_observacion varchar(50) NOT NULL DEFAULT 'SinObservaciones',
    imagen_url text NULL,
    aplicar_productos boolean NOT NULL DEFAULT true,
    aplicar_ingredientes boolean NOT NULL DEFAULT false,
    aplicar_delivery boolean NOT NULL DEFAULT false,
    aplicar_salon boolean NOT NULL DEFAULT false,
    mostrar_carta_digital boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ix_subrubros_empresa_rubro ON subrubros(id_empresa, id_rubro);

CREATE TABLE IF NOT EXISTS alicuotas (
    id_alicuota integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre varchar(100) NOT NULL,
    descripcion varchar(500) NOT NULL,
    porcentaje numeric(5,2) NOT NULL CHECK (porcentaje >= 0 AND porcentaje <= 100),
    activa boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_alicuotas_global_nombre
    ON alicuotas(nombre) WHERE id_empresa IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_alicuotas_empresa_nombre
    ON alicuotas(id_empresa, nombre) WHERE id_empresa IS NOT NULL;

INSERT INTO alicuotas (id_empresa, nombre, descripcion, porcentaje, activa)
SELECT NULL, 'IVA 21%', 'Impuesto al Valor Agregado', 21.00, true
WHERE NOT EXISTS (
    SELECT 1 FROM alicuotas WHERE id_empresa IS NULL AND nombre = 'IVA 21%'
);

CREATE TABLE IF NOT EXISTS producto_codigo_contadores (
    id_empresa integer PRIMARY KEY REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    ultimo_codigo integer NOT NULL CHECK (ultimo_codigo > 0)
);

CREATE TABLE IF NOT EXISTS productos (
    id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa integer NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    codigo integer NOT NULL CHECK (codigo > 0),
    nombre varchar(200) NOT NULL,
    descripcion varchar(2000) NULL,
    tipo_producto varchar(50) NOT NULL DEFAULT 'ProductoSimple',
    id_rubro integer NOT NULL REFERENCES rubros(id_rubro) ON DELETE RESTRICT,
    id_subrubro integer NULL REFERENCES subrubros(id_subrubro) ON DELETE RESTRICT,
    id_alicuota integer NOT NULL REFERENCES alicuotas(id_alicuota) ON DELETE RESTRICT,
    costo_con_iva numeric(18,2) NOT NULL CHECK (costo_con_iva >= 0),
    precio_con_iva numeric(18,2) NOT NULL CHECK (precio_con_iva >= 0),
    imagen_url text NULL,
    activo boolean NOT NULL DEFAULT true,
    mostrar_delivery boolean NOT NULL DEFAULT false,
    mostrar_salon boolean NOT NULL DEFAULT false,
    mostrar_carta_digital boolean NOT NULL DEFAULT false,
    solicitar_cantidad boolean NOT NULL DEFAULT false,
    solicitar_precio_unitario boolean NOT NULL DEFAULT false,
    solicitar_precio_y_calcular_cantidad boolean NOT NULL DEFAULT false,
    preparacion varchar(4000) NULL,
    orden integer NOT NULL DEFAULT 0,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_productos_empresa_codigo UNIQUE (id_empresa, codigo)
);

CREATE INDEX IF NOT EXISTS ix_productos_empresa_activo ON productos(id_empresa, activo);
CREATE INDEX IF NOT EXISTS ix_productos_empresa_rubro ON productos(id_empresa, id_rubro);
CREATE INDEX IF NOT EXISTS ix_productos_subrubro ON productos(id_subrubro);
CREATE INDEX IF NOT EXISTS ix_productos_nombre ON productos(id_empresa, nombre);

CREATE TABLE IF NOT EXISTS stock_productos (
    id_stock_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto integer NOT NULL REFERENCES productos(id_producto) ON DELETE CASCADE,
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal) ON DELETE RESTRICT,
    operacion_cantidad varchar(20) NOT NULL DEFAULT 'Entero'
        CHECK (operacion_cantidad IN ('Entero', 'Decimal')),
    stock_actual numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    stock_minimo numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    stock_ideal numeric(18,3) NOT NULL DEFAULT 0 CHECK (stock_ideal >= stock_minimo),
    tiene_alarma_stock boolean NOT NULL DEFAULT false,
    tiene_alarma_stock_minimo boolean NOT NULL DEFAULT false,
    comprobar_stock_al_vender boolean NOT NULL DEFAULT false,
    actualizar_sobre varchar(20) NOT NULL DEFAULT 'Producto'
        CHECK (actualizar_sobre IN ('Producto', 'Ingrediente')),
    fecha_modificacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_stock_productos_producto_sucursal UNIQUE (id_producto, id_sucursal)
);

CREATE INDEX IF NOT EXISTS ix_stock_productos_sucursal ON stock_productos(id_sucursal);

COMMIT;
